<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>SSHProxyManager</AssemblyName>
    <RootNamespace>SSHProxyManager</RootNamespace>
    <Nullable>enable</Nullable>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    
    <!-- اطلاعات سازنده و ورژن -->
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Authors>Mohammad Hossein Soleymani (MHS)</Authors>
    <Company>MHS</Company>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SSH.NET" Version="2024.2.0" />
    <Resource Include="icon.ico" />
  </ItemGroup>
</Project>