<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>

    <!-- ✅ مخصوص مک‌او‌اس - اپل سیلیکون -->
    <RuntimeIdentifier>osx-arm64</RuntimeIdentifier>
    <UseAppHost>true</UseAppHost>

    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Authors>Mohammad Hossein Soleymani (MHS)</Authors>
    <Company>MHS</Company>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.0" />
    <PackageReference Include="Avalonia.Desktop" Version="11.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.0" />
    <PackageReference Include="SSH.NET" Version="2024.2.0" />
  </ItemGroup>
</Project>